# Global
http://localhost:8080/api/v1/event
--

--
# Get a list of events
GET /list

--
GET /1
# Get event with id

--
# Get suitable date for event with id
GET /1/results

--
# Post a new event
POST /
{
    "name": "Test Event 1",
    "dates": [
        "2014-01-01",
        "2014-01-05",
        "2014-01-12"
    ]
}

--
# Post a vote of dates for an event
POST /1/vote
{
    "name": "Test Person 1",
    "votes": [
        "2014-01-01"
    ]
}
