version: "3.3"

services:

  apigateway:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - "./deployment/nginx.docker.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - external
      - internal

  event-service:
    build:
      context: ./event-service
    environment:
      PORT: 9000
      DB_TYPE: "mariadb"
      DB_HOST: "mariadb"
      DB_PORT: 3306
      DB_USERNAME: "root"
      DB_PASSWORD: "root"
      DB_DATABASE: "test"
      DB_RECONNECTION_TRIES: 10
      DB_RECONNECTION_INTERVAL: 5000
      DB_SYNCHRONIZE: "true"
      ROUTE_PREFIX: "/api/v1/event"
    expose:
      - "9000"
    ports:
      - 9000:9000
    networks:
      - internal

  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test"
    volumes:
      - "./__data__:/var/lib/mysql:rw"
    ports:
      - 3306:3306
    networks:
      - internal

networks:
  internal:
    external: false
  external:
    external: true
