apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - event-service-service.yml
  - event-service-configmap.yml
  - mariadb-service.yml
  - mariadb-configmap.yml
  - ingress.yml
