# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, test and deploy to GKE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: cd event-service
    
    - name: Install
      run: npm ci
     
    # Run linting to make sure project coding style is kept
    - name: Run linter
      run: npm run lint
    
    # Build the project
    - name: Build
      run: npm run build --if-present
      
    # Run tests
    - name: Run unit tests
      run: npm run test:unit
